export const authentificationModalVisibilityFilters = {
    SHOW_LOGIN: 'SHOW_LOGIN',
    SHOW_CHOOSE_ROLE: 'SHOW_CHOOSE_ROLE',
    SHOW_REGISTER_RESTAURANT_OWNER: 'SHOW_REGISTER_RESTAURANT_OWNER',
    SHOW_REGISTER_CUSTOMER: 'SHOW_REGISTER_CUSTOMER',
    HIDE_ALL: 'HIDE_ALL'
}