export const modalVisibilityFilters = {
    SHOW_LOGIN: "SHOW_LOGIN",
    SHOW_LOGOUT: "SHOW_LOGOUT",
    SHOW_REGISTER_RESTAURANT_OWNER: "SHOW_REGISTER_RESTAURANT_OWNER",
    SHOW_RESTAURANT_INFORMATION: "SHOW_RESTAURANT_INFORMATION",
    SHOW_EDIT_RESTAURANT_INFORMATION: "SHOW_EDIT_RESTAURANT_INFORMATION",
    SHOW_ADD_MENU: "SHOW_ADD_MENU",
    SHOW_EDIT_MENU: "SHOW_EDIT_MENU",
    SHOW_ADD_DISH: "SHOW_ADD_DISH",
    SHOW_EDIT_DISH: "SHOW_EDIT_DISH",
    SHOW_ADD_DRINK: "SHOW_ADD_DRINK",
    SHOW_EDIT_DRINK: "SHOW_EDIT_DRINK",
    HIDE_ALL: "HIDE_ALL"
};