export const modalVisibilityFilters = {
    SHOW_LOGIN: 'SHOW_LOGIN',
    //SHOW_CHOOSE_ROLE: 'SHOW_CHOOSE_ROLE', TO REMOVE
    SHOW_REGISTER_RESTAURANT_OWNER: 'SHOW_REGISTER_RESTAURANT_OWNER',
    //SHOW_REGISTER_CUSTOMER: 'SHOW_REGISTER_CUSTOMER', TO REMOVE
    SHOW_RESTAURANT_INFORMATION: "SHOW_RESTAURANT_INFORMATION",
    SHOW_EDIT_RESTAURANT_INFORMATION: 'SHOW_EDIT_RESTAURANT_INFORMATION',
    SHOW_ADD_MENU: 'SHOW_ADD_MENU',
    SHOW_EDIT_MENU: 'SHOW_EDIT_MENU',
    HIDE_ALL: 'HIDE_ALL'
};