// noinspection JSLint
export const modals = {
    SHOW_LOGIN:                     "SHOW_LOGIN",
    SHOW_LOGIN_CONSULTANT:          "SHOW_LOGIN_CONSULTANT",
    SHOW_LOGOUT:                    "SHOW_LOGOUT",
    SHOW_CHOOSE_ROLE:               "SHOW_CHOOSE_ROLE",
    SHOW_REGISTER_RESTAURANT_OWNER: "SHOW_REGISTER_RESTAURANT_OWNER",
    SHOW_REGISTER_CUSTOMER:         "SHOW_REGISTER_REGISTER_CUSTOMER",
    SHOW_REGISTER_CONSULTANT:       "SHOW_REGISTER_CONSULTANT",
    SHOW_ADD_RESTAURANT:            "SHOW_ADD_RESTAURANT",
    SHOW_EDIT_RESTAURANT:           "SHOW_EDIT_RESTAURANT",
    SHOW_ADD_MENU:                  "SHOW_ADD_MENU",
    SHOW_EDIT_MENU:                 "SHOW_EDIT_MENU",
    SHOW_PENDING_REVIEW:            "SHOW_PENDING_REVIEW",
    SHOW_ADD_DISH:                  "SHOW_ADD_DISH",
    SHOW_EDIT_DISH:                 "SHOW_EDIT_DISH",
    SHOW_ADD_DRINK:                 "SHOW_ADD_DRINK",
    SHOW_EDIT_DRINK:                "SHOW_EDIT_DRINK",
    SHOW_CHANGE_PASSWORD:           "SHOW_CHANGE_PASSWORD",
    HIDE_ALL:                       "HIDE_ALL"
};