language: node_js
node_js:
  - "13"
cache:
  directories:
    - $HOME/node_modules
env:
  global:
    - theSpoon_jwtPrivateKey=mySecureKey
branches:
  only:
    - travis
    - dev
    - master
script:
  - echo "Temporary message"
