export const REGISTERING_ATTEMPTING = 'REGISTERING_ATTEMPTING';
export const REGISTERING_FAILING = 'REGISTERING_FAILING';
export const REGISTERING_SUCCESSING = 'REGISTERING_SUCCESSING';
export const LOGGING_IN_ATTEMPTING = 'LOGGING_IN_ATTEMPTING';
export const LOGGING_IN_FAILING = 'LOGGING_IN_FAILING';
export const LOGGING_IN_SUCCESSING = 'LOGGING_IN_SUCCESSING';
export const LOGGING_OUT = 'LOGGING_OUT';
