export const LOGGING_IN_ATTEMPTING = "LOGGING_IN_ATTEMPTING";
export const LOGGING_IN_FAILING = "LOGGING_IN_FAILING";
export const LOGGING_IN_SUCCESSING = "LOGGING_IN_SUCCESSING";
export const LOGGING_OUT = "LOGGING_OUT";